redirects:
  getting-started: quick-start/getting-started.md
  getting-started/10-set-up-platform-agents: quick-start/set-up-agents/README.md
  getting-started/15-deploy-example-application: quick-start/deploy-example-application/README.md
  getting-started/30-run-experiment: quick-start/run-experiment/README.md
  install-configure: install-and-configure/install-agent/README.md
  install-configure/30-install-agents: install-and-configure/install-agent/README.md
  install-configure/30-install-agents/10-docker: install-and-configure/install-agent/install-as-docker-container.md
  install-configure/30-install-agents/20-kubernetes: install-and-configure/install-agent/install-on-kubernetes.md
  install-configure/30-install-agents/30-host: install-and-configure/install-agent/install-on-linux-hosts.md
  install-configure/30-install-agents/30-host-windows: install-and-configure/install-agent/install-on-windows-hosts.md
  install-configure/30-install-agents/35-aws-ecs-ec2: install-and-configure/install-agent/aws-ecs-ec2.md
  install-configure/30-install-agents/40-aws-cloud: install-and-configure/install-agent/README.md
  install-configure/30-install-agents/50-advanced-configuration: install-and-configure/install-agent/advanced-configuration.md
  install-configure/30-install-agents/50-faq: troubleshooting/agent.md
  install-and-configure: install-and-configure/install-agent/README.md
  install-and-configure/install-agents: install-and-configure/install-agent/README.md
  install-and-configure/install-agents/docker: install-and-configure/install-agent/install-as-docker-container.md
  install-and-configure/install-agents/kubernetes: install-and-configure/install-agent/install-on-kubernetes.md
  install-and-configure/install-agents/host: install-and-configure/install-agent/install-on-linux-hosts.md
  install-and-configure/install-agents/host-windows: install-and-configure/install-agent/install-on-windows-hosts.md
  install-and-configure/install-agents/aws-ecs-ec2: install-and-configure/install-agent/aws-ecs-ec2.md
  install-and-configure/install-agents/aws-cloud: install-and-configure/install-agent/README.md
  install-and-configure/install-agents/advanced-configuration: install-and-configure/install-agent/advanced-configuration.md
  install-and-configure/install-agents/faq: troubleshooting/agent.md
  install-and-configure/install-agent/extension-discovery: install-and-configure/install-agent/extension-registration.md
  install-and-configure/install-outpost-agent-preview: install-and-configure/install-agent/README.md
  install-and-configure/install-outpost-agent-preview/outpost-agent-architecture: install-and-configure/install-agent/agent-architecture.md
  install-and-configure/install-outpost-agent-preview/install-on-kubernetes: install-and-configure/install-agent/install-on-kubernetes.md
  install-and-configure/install-outpost-agent-preview/install-on-linux-hosts: install-and-configure/install-agent/install-on-linux-hosts.md
  install-and-configure/install-outpost-agent-preview/install-on-windows-hosts: install-and-configure/install-agent/install-on-windows-hosts.md
  install-and-configure/install-outpost-agent-preview/install-as-docker-container: install-and-configure/install-agent/install-as-docker-container.md
  install-and-configure/install-outpost-agent-preview/aws-ecs-ec2: install-and-configure/install-agent/aws-ecs-ec2.md
  install-and-configure/install-outpost-agent-preview/extension-discovery: install-and-configure/install-agent/extension-registration.md
  install-and-configure/install-outpost-agent-preview/using-mutual-tls-for-extensions: install-and-configure/install-agent/using-mutual-tls-for-extensions.md
  install-and-configure/install-outpost-agent-preview/advanced-configuration: install-and-configure/install-agent/advanced-configuration.md
  install-and-configure/install-outpost-agent: install-and-configure/install-agent/README.md
  install-and-configure/install-outpost-agent/outpost-agent-architecture: install-and-configure/install-agent/agent-architecture.md
  install-and-configure/install-outpost-agent/install-on-kubernetes: install-and-configure/install-agent/install-on-kubernetes.md
  install-and-configure/install-outpost-agent/install-on-linux-hosts: install-and-configure/install-agent/install-on-linux-hosts.md
  install-and-configure/install-outpost-agent/install-on-windows-hosts: install-and-configure/install-agent/install-on-windows-hosts.md
  install-and-configure/install-outpost-agent/install-as-docker-container: install-and-configure/install-agent/install-as-docker-container.md
  install-and-configure/install-outpost-agent/aws-ecs-ec2: install-and-configure/install-agent/aws-ecs-ec2.md
  install-and-configure/install-outpost-agent/extension-discovery: install-and-configure/install-agent/extension-registration.md
  install-and-configure/install-outpost-agent/using-mutual-tls-for-extensions: install-and-configure/install-agent/using-mutual-tls-for-extensions.md
  install-and-configure/install-outpost-agent/advanced-configuration: install-and-configure/install-agent/advanced-configuration.md
  install-configure/40-install-platform: install-and-configure/install-on-prem-platform/README.md
  install-and-configure/install-on-prem-platform/k8s: install-and-configure/install-on-prem-platform/README.md
  install-configure/40-install-platform/10-docker: install-and-configure/install-on-prem-platform/README.md
  install-configure/40-install-platform/20-k8s: install-and-configure/install-on-prem-platform/README.md
  install-configure/40-install-platform/30-advanced-configuration: install-and-configure/install-on-prem-platform/advanced-configuration.md
  install-configure/50-set-up-environments: install-and-configure/manage-environments/README.md
  install-configure/60-teams-and-users: install-and-configure/manage-teams-and-users/README.md
  install-configure/60-teams-and-users/10-teams: install-and-configure/manage-teams-and-users/teams.md
  install-configure/60-teams-and-users/20-users: install-and-configure/manage-teams-and-users/users.md
  install-configure/60-teams-and-users/30-permissions: install-and-configure/manage-teams-and-users/permissions.md
  install-configure/70-configure-monitoring: concepts/actions/README.md
  install-configure/70-configure-monitoring/10-datadog: concepts/actions/README.md
  install-configure/70-configure-monitoring/20-instana: concepts/actions/README.md
  install-configure/70-configure-monitoring/30-new-relic: concepts/actions/README.md
  install-configure/70-configure-monitoring/40-prometheus: concepts/actions/README.md
  installation-platform/3-advanced-configuration: install-and-configure/install-on-prem-platform/advanced-configuration.md
  use: use-steadybit/experiments/README.md
  use/10-experiments: use-steadybit/experiments/README.md
  use/10-experiments/10-design: use-steadybit/experiments/design.md
  use/10-experiments/20-run: use-steadybit/experiments/run.md
  use/10-experiments/30-prevent-execution: use-steadybit/experiments/emergencyStop.md
  use/20-landscape: use-steadybit/explorer/README.md
  use/30-weakspots: use-steadybit/explorer/advice.md
  use-steadybit/landscape: use-steadybit/explorer/README.md
  use-steadybit/weakspots: use-steadybit/explorer/advice.md
  learn: install-and-configure/install-agent/agent-architecture.md
  learn/10-architecture: install-and-configure/install-agent/agent-architecture.md
  learn/15-actions: concepts/actions/README.md
  learn/15-actions/10-pod-count: concepts/actions/README.md
  learn/15-actions/20-http-call: concepts/actions/README.md
  learn/15-actions/30-prometheus: concepts/actions/README.md
  learn/15-actions/40-postman: concepts/actions/README.md
  learn/20-attacks: use-steadybit/actions.md
  learn/20-attacks/application: use-steadybit/actions.md
  learn/20-attacks/kubernetes: use-steadybit/actions.md
  learn/20-attacks/network: use-steadybit/actions.md
  learn/20-attacks/resource: use-steadybit/actions.md
  learn/20-attacks/state: use-steadybit/actions.md
  learn/30-discovery: use-steadybit/discovery/README.md
  learn/30-discovery/10-host: concepts/discovery/README.md
  learn/30-discovery/20-container: concepts/discovery/README.md
  learn/30-discovery/30-application: concepts/discovery/README.md
  learn/30-discovery/40-cloud: concepts/discovery/README.md
  learn/30-discovery/50-custom: integrate-with-steadybit/extensions/README.md
  learn/40-loadtests: concepts/actions/README.md
  learn/50-monitoring: concepts/actions/README.md
  learn/70-audit-log: integrate-with-steadybit/audit-log.md
  integrate: concepts/actions/README.md
  integrate/10-api: integrate-with-steadybit/api/api.md
  integrate/15-cli: integrate-with-steadybit/cli.md
  integrate/20-loadtests: concepts/actions/README.md
  integrate/20-loadtests/10-gatling: concepts/actions/README.md
  integrate/20-loadtests/20-jmeter: concepts/actions/README.md
  integrate/20-loadtests/30-k6: concepts/actions/README.md
  integrate/30-monitoring: concepts/actions/README.md
  integrate/30-monitoring/10-datadog: concepts/actions/README.md
  integrate/30-monitoring/30-instana: concepts/actions/README.md
  integrate/30-monitoring/40-newrelic: concepts/actions/README.md
  integrate/30-monitoring/50-prometheus: concepts/actions/README.md
  integrate/40-slack-notifications: integrate-with-steadybit/slack-notifications.md
  integrate/50-webhooks: integrate-with-steadybit/webhooks.md
  docs: getting-started.md
  use-steadybit/attacks/README: use-steadybit/actions.md
  use-steadybit/attacks: use-steadybit/actions.md
  use-steadybit/attacks/state: use-steadybit/actions.md
  use-steadybit/attacks/resource: use-steadybit/actions.md
  use-steadybit/attacks/network: use-steadybit/actions.md
  use-steadybit/attacks/kubernetes: use-steadybit/actions.md
  use-steadybit/attacks/application: use-steadybit/actions.md
  use-steadybit/attacks/aws-cloud-attacks: use-steadybit/actions.md
  use-steadybit/checks/README: use-steadybit/actions.md
  use-steadybit/checks: use-steadybit/actions.md
  use-steadybit/checks/pod-count: use-steadybit/actions.md
  use-steadybit/checks/http-call: use-steadybit/actions.md
  use-steadybit/checks/prometheus: use-steadybit/actions.md
  use-steadybit/checks/postman: use-steadybit/actions.md
  use-steadybit/discovery/application: use-steadybit/discovery/README.md
  use-steadybit/discovery/cloud: use-steadybit/discovery/README.md
  use-steadybit/discovery/container: use-steadybit/discovery/README.md
  use-steadybit/discovery/custom: use-steadybit/discovery/README.md
  use-steadybit/discovery/host: use-steadybit/discovery/README.md
  use-steadybit/load-tests/README: use-steadybit/actions.md
  use-steadybit/load-tests: use-steadybit/actions.md
  use-steadybit/load-tests/gatling: use-steadybit/actions.md
  use-steadybit/load-tests/jmeter: use-steadybit/actions.md
  use-steadybit/load-tests/k6: use-steadybit/actions.md
  getting-started/20-define-resilience-expectations: getting-started.md
  quick-start/define-resilience-expectations: getting-started.md
  use-steadybit/resilience-policies: use-steadybit/experiments/README.md
  use-steadybit/resilience-policies/references: use-steadybit/experiments/README.md
  use-steadybit/resilience-policies/taskandpolicydefinitions: use-steadybit/experiments/README.md
  use-steadybit/resilience-policies/ymlDownloadViaUI: use-steadybit/experiments/README.md
  use-steadybit/resilience-expectations: use-steadybit/experiments/README.md
  learn/60-resilience-expectations: use-steadybit/experiments/README.md
  learn/60-resilience-expectations/10-introduction: use-steadybit/experiments/README.md
  learn/60-resilience-expectations/20-definition: use-steadybit/experiments/README.md
  use-steadybit/query-language: concepts/query-language/README.md
  use-steadybit/actions: concepts/actions/README.md
  use-steadybit/discovery: concepts/discovery/README.md
  use-steadybit/experiments/share/yml-import-export: use-steadybit/experiments/file-import-export/README.md
  install-and-configure/configure-monitoring: concepts/actions/README.md
  install-and-configure/configure-monitoring/datadog: concepts/actions/README.md
  install-and-configure/configure-monitoring/instana: concepts/actions/README.md
  install-and-configure/configure-monitoring/new-relic: concepts/actions/README.md
  install-and-configure/configure-monitoring/newrelic: concepts/actions/README.md
  install-and-configure/configure-monitoring/prometheus: concepts/actions/README.md
  integrate-with-steadybit/monitoring: concepts/actions/README.md
  integrate-with-steadybit/monitoring/datadog: concepts/actions/README.md
  integrate-with-steadybit/monitoring/instana: concepts/actions/README.md
  integrate-with-steadybit/monitoring/newrelic: concepts/actions/README.md
  integrate-with-steadybit/monitoring/prometheus: concepts/actions/README.md
  integrate-with-steadybit/extensions/available-extensions: integrate-with-steadybit/extensions/README.md
  troubleshooting/extension: troubleshooting/common-fixes/extensions.md
  troubleshooting/agent: troubleshooting/common-fixes/agents.md
  troubleshooting/on-prem-platform: troubleshooting/common-fixes/on-prem-platform.md
