name: Check Redirects
on:
  workflow_dispatch:

jobs:
  check_redirects:
    runs-on: ubuntu-latest
    name: Check Redirects Job
    timeout-minutes: 60
    steps:
      - name: Give GitBook a few seconds till it has processed everything
        run: sleep 60s
        shell: bash
        if: "!cancelled()"

      - name: Check Redirects
        uses: steadybit/gitbook-redirect-checker@v0.3
        if: "!cancelled()"

      - name: Notify Slack channel
        uses: 8398a7/action-slack@1750b5085f3ec60384090fb7c52965ef822e869e # v3.18.9
        with:
          channel: '#test-docs'
          status: ${{ job.status }}
          text: Found broken redirects in docs
          fields: workflow,action
          author_name: github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: failure()
