name: Check Redirects
on:
  workflow_dispatch:

jobs:
  check_redirects:
    runs-on: ubuntu-latest
    name: Check Redirects Job
    timeout-minutes: 60
    steps:
      - name: Give GitBook a few seconds till it has processed everything
        run: sleep 60s
        shell: bash
        if: "!cancelled()"

      - name: Check Redirects
        uses: steadybit/gitbook-redirect-checker@v0.3
        if: "!cancelled()"

      - name: Notify Slack channel
        uses: act10ns/slack@d96404edccc6d6467fc7f8134a420c851b1e9054 # v2.2.0
        with:
          channel: '#test-docs'
          status: ${{ job.status }}
          message: "Found broken redirects in docs"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: failure()
